# Generated by Django 5.1.3 on 2024-12-23 23:37

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_id_alter_eventparticipant_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23ede961-7847-442d-b0d0-87d7bf30a320'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23ede961-7847-442d-b0d0-87d7bf30a320'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['active'], name='events_even_active_926381_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['deleted_at'], name='events_even_deleted_61e684_idx'),
        ),
    ]
