# Generated by Django 5.1.3 on 2024-12-23 23:37

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_id_alter_eventparticipant_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2cfbae68-e4f0-4b1a-9840-5dc7e01b8bfa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2cfbae68-e4f0-4b1a-9840-5dc7e01b8bfa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['active'], name='events_even_active_7d8b88_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['deleted_at'], name='events_even_deleted_18e102_idx'),
        ),
    ]
