# Generated by Django 5.1.3 on 2025-04-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_eventuser_email_alter_eventuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
