# Generated by Django 5.1.3 on 2024-11-17 20:51

import authentication.enum.role
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.IntegerField(choices=[(1, 'ORGANIZER'), (2, 'PARTICIPANT'), (3, 'ADMIN')], default=authentication.enum.role.Role['PARTICIPANT']),
        ),
    ]
