# Generated by Django 5.1.3 on 2024-11-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_phone_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.IntegerField(choices=[(1, 'ORGANIZER'), (2, 'PARTICIPANT'), (3, 'ADMIN')], default=2),
        ),
    ]
